# goバージョン
FROM golang:1.16.3-alpine

# ワーキングディレクトリの設定
WORKDIR /go_prog

# アップデートとgitのインストール
RUN apk add --update \
    && apk apk add --no-cache alpine-sdk git \
    && go get -u github.com/oxequa/realize

EXPOSE 8080
CMD ["realize", "start"]



