version: "3"
services: 
  go_prog: # go言語の学習用
    build:
      context: ./go_prog
      dockerfile: Dockerfile_goProg
    ports:
      - 50500:8080
    volumes:
      - ./go_prog:/go_prog # マウントディレクトリ
  first_webapp: # webアプリ
    build: 
      context: ./go_prog
      dockerfile: Dockerfile_firstWebapp
    ports: 
      - 50501:8080
    volumes:
      - ./go_prog:/go/app # マウントディレクトリ
  one_more_advice_db_prog:
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: one_more_advice_prog
            MYSQL_DATABASE: one_more_advice_prog
        ports:
            - 4307:3306
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
